#' PCs from transcripts
#'
#'  This function returns the pcs from the obtained RangedSummarizedExperiment object of selected transcripts
#'
#'
#' @param covComb_tx Ranged Summarizeed Experiment with only trancsripts selected for qsva
#'
#' @return prcomp object generated by taking the pcs of degraded transcripts
#' @export
#' @importFrom stats prcomp
#' @importFrom SummarizedExperiment assays
#' @examples
#' getBonfTx(covComb_tx_deg)
#'  ## TODO
getBonfTx<- function(covComb_tx){
        qsvBonf_tx<-prcomp(t(log2(assays(covComb_tx)$tpm+1)))
}
