#' SomeTITLE
#'
#'  TODO some description.
#'
#'
#' @param covComb_tx Ranged Summarizeed Experiment with only trancsripts selected for qsva
#'
#' @return prcomp object generated by taking the pcs of degraded transcripts
#' @export
#' @importFrom stats prcomp
#' @importFrom SummarizedExperiment assays
#' @examples
#'  ## TODO
getBonfTx<- function(covComb_tx){
        qsvBonf_tx<-prcomp(t(log2(assays(covComb_tx)$tpm+1)))
}
