#' PCs from features
#'
#' This function returns the pcs from the obtained RangedSummarizedExperiment object of selected features
#'
#' @param rse Ranged Summarizeed Experiment with only features selected for qsva
#' @param assayname character string specifying the name of the assay desired in rse
#'
#' @return prcomp object generated by taking the pcs of degraded features
#' @export
#' @importFrom stats prcomp
#' @import SummarizedExperiment
#' @examples
#' getPCs(rse, "tpm")
getPCs <- function(rse, assayname = "tpm") {
    # Validate rse is a RangedSummarizedExperiment object
    if (!is(rse, "RangedSummarizedExperiment")) {
        stop("'rse' must be a RangedSummarizedExperiment object.", call. = FALSE)
    }

    # Check if assayname is in assayNames
    if (!assayname %in% assayNames(rse)) {
        stop(sprintf("'%s' is not in assayNames(rse).", assayname), call. = FALSE)
    }
    # Compute PCs
    qsvPCs <- prcomp(t(log2(assays(rse)[[assayname]] + 1)))
}
